---
- stat: path=~{{ user }}/.dotfiles
  register: dotfiles_dir

- name: Clone dotfiles for {{ user }}
  become: yes
  become_user: "{{ user }}"
  git: repo={{ dotfiles_repo_url }} dest={{ dotfiles_dir }} accept_hostkey=yes update=no
  register: df_clone
  when: not dotfiles_dir.stat.exists
